stages:
  - build
  - deploy

variables:
  NPM_CONFIG_CACHE: '$CI_PROJECT_DIR/.npm'
  NPM_CONFIG_PROXY: 'http://proxygeadm.etat-ge.ch:3128'
  NPM_CONFIG_HTTPS_PROXY: 'http://proxygeadm.etat-ge.ch:3128'
  NPM_CONFIG_NOPROXY: 'etat-ge.ch'
  NPM_CONFIG_REGISTRY: 'https://registry.devops.etat-ge.ch/ctinexus/content/repositories/npm-all/'

build:
  stage: build
  image: docker-all.devops.etat-ge.ch/library/node:20.11.1
  tags:
    - docker
  script:
    - npm ci
    - npm run build
  artifacts:
    when: on_success
    paths:
      - dist/

build-and-publish-docker-image:
  stage: build
  image: buildah/stable:v1.30.0
  tags:
    - docker
  needs:
    - build
  variables:
    GIT_DEPTH: 1
    GIT_STRATEGY: clone
    PUBLISH_REGISTRY: "oci-snapshot.devops.etat-ge.ch"
    BUILDING_IMAGE_TAG: "latest"
    BUILDING_IMAGE_NAME: "ch/ge/afc/rapports-bdd"
  script:
    - buildah version
    - |
      if [ -z "$PUBLISH_REGISTRY" ]
      then
        export PUBLISH_REGISTRY="$DOCKER_RELEASE_REGISTRY"
      fi
    - 'echo "Registry de publication image : $PUBLISH_REGISTRY"'
    - echo "${PASS_USER_TECHNIQUE_GIT}" | buildah login --username "${USER_TECHNIQUE_GIT}"
      --password-stdin "${PUBLISH_REGISTRY}"
    - export FULL_IMAGE_NAME="$PUBLISH_REGISTRY/$BUILDING_IMAGE_NAME:$BUILDING_IMAGE_TAG"
    - 'echo "Image : $FULL_IMAGE_NAME"'
    - |
      if [ -z "$BUILDING_IMAGE_DIR" ]
      then
        export BUILDING_IMAGE_DIR="."
      fi
    - cd $BUILDING_IMAGE_DIR
    - buildah bud -f Dockerfile --format docker -t ${FULL_IMAGE_NAME} .
    - buildah push ${FULL_IMAGE_NAME}
    - cd -
    - buildah logout "${PUBLISH_REGISTRY}"

restart-openshift-deployment:
  stage: deploy
  image: ch/ge/afc/oce-cli
  tags:
    - docker
  when: on_success
  variables:
    GIT_STRATEGY: none
  script:
    - oc login --insecure-skip-tls-verify --token=$OPENSHIFT_PROJECT_TOKEN --server=https://api.soca.lbdev.etat-ge.ch:6443
    - oc rollout restart deployment/deployment-rapports-bdd
